FROM node:10-alpine
WORKDIR /usr/src/app

COPY ./${SERVICE_NAME} .

RUN apk add --no-cache chromium nss
ENV CHROME_BIN=/usr/bin/chromium-browser

RUN npm install -global pm2

RUN npm install --production 

EXPOSE ${SERVICE_PORT}

CMD [ "pm2-runtime", "pm2.json" ]